"""
Fiscal Sustainability Dashboard: data fetcher
=============================================
Fetches monthly 10Y yields from FRED and WEO fiscal and macro variables from
the IMF, validates them, carries forward anything that could not be
refreshed, and writes:

    data/fiscal_data.json   the dashboard data (fetched over http://)
    data/fiscal_data.js     the same data as a script (works over file://)
    data/history.json       one snapshot per run, for change over time
    data/imf_vintages.json  every IMF release seen, for revisions

The run does not stop on a data problem. See pipeline/run.py.

Usage:
    python scripts/fetch_data.py
    FRED_API_KEY is optional. Without it the public FRED CSV endpoint is used.
    RUN_DATE=YYYY-MM-DD overrides today's date, for testing.
"""

import json
import os
import sys
from datetime import date
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from pipeline import dynamics, fred, history, imf, vintages  # noqa: E402
from pipeline.config import OUTPUT_FILE, OUTPUT_JS_FILE, OVERRIDES_FILE  # noqa: E402
from pipeline.run import build  # noqa: E402


def load_json(path):
    if path.exists():
        return json.loads(path.read_text(encoding="utf-8"))
    return None


def write_outputs(output):
    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_FILE.write_text(json.dumps(output, indent=2) + "\n", encoding="utf-8")
    OUTPUT_JS_FILE.write_text(
        "// Auto-generated by scripts/fetch_data.py. Do not edit manually.\n"
        "window.FISCAL_DATA = " + json.dumps(output, separators=(",", ":")) + ";\n",
        encoding="utf-8")


def main():
    run_date = date.fromisoformat(os.environ["RUN_DATE"]) if os.environ.get("RUN_DATE") else date.today()
    api_key = os.environ.get("FRED_API_KEY") or None
    if not api_key:
        print("Note: FRED_API_KEY not set, using the public FRED CSV endpoint.")

    archive = vintages.load()
    hist = history.load()
    output = build(
        run_date,
        fetch_yield=lambda series: fred.fetch_monthly(series, api_key),
        fetch_sdmx=imf.fetch_sdmx,
        fetch_datamapper=imf.fetch_datamapper,
        previous_output=load_json(OUTPUT_FILE),
        archive=archive,
        overrides=load_json(OVERRIDES_FILE) or {},
    )

    dynamics.attach(output, hist, archive, run_date)
    write_outputs(output)
    vintages.save(archive)
    history.upsert(hist, history.make_entry(run_date, "live", output["imf"]["vintage"],
                                            output["projection_year"], output["countries"]))
    history.save(hist)

    print(f"Run date {run_date} | {output['data_vintage']} | IMF source: {output['imf']['source']}")
    for c in output["countries"]:
        marks = ",".join(sorted({f["kind"] for f in c["flags"]}))
        print(f"  {c['name']:16s} r={c['r']:5.2f} ({c['r_month']}) g={c['g']:5.2f} "
              f"pb={c['pb']:+6.2f} debt={c['debt']:6.1f} gap={c['fiscal_gap']:+.2f} {marks}")
    for line in output["data_status"]:
        print(f"  STATUS: {line}")
    if output.get("skipped"):
        print(f"  SKIPPED (no data at all): {output['skipped']}")


if __name__ == "__main__":
    main()
